name: fastplong ci
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout scm
        uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: install build dependencies (Ubuntu)
        run: sudo apt update && sudo apt install -y build-essential nasm libgtest-dev libhwy-dev libisal-dev
        if: runner.os == 'Linux'

      - name: install build dependencies (MacOS)
        run: brew install highway googletest isa-l
        if: runner.os == 'macOS'

      - name: get deflate
        uses: actions/checkout@v3
        with:
          repository: ebiggers/libdeflate
          path: src/libs/deflate
          ref: v1.22

      - name: build deflate
        run: |
          cd src/libs/deflate
          cmake -B build
          cmake --build build -j ${{ steps.cpu-cores.outputs.count }}
          sudo cmake --install build
          cd -

      - name: make fastplong
        run: bash -c 'make -j $(nproc)'

      - name: make test
        run: bash -c 'make -j $(nproc) test'

      - name: test
        run: chmod a+x ./fastplong && ./fastplong --version

