name: fastplong ci
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout scm
        uses: actions/checkout@v3

      - name: install build dependencies (Ubuntu)
        run: sudo apt update && sudo apt install -y build-essential libgtest-dev libhwy-dev libisal-dev libdeflate-dev
        if: runner.os == 'Linux'

      - name: install build dependencies (MacOS)
        run: brew install highway googletest isa-l libdeflate
        if: runner.os == 'macOS'

      - name: make fastplong
        run: make -j

      - name: make test
        run: make -j test

      - name: test
        run: chmod a+x ./fastplong && ./fastplong --version

